const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

// Usage: node decrypt_log.cjs <path_to_bpplog_file>

const args = process.argv.slice(2);
if (args.length === 0) {
    console.error('Please provide the path to the .bpplog file as an argument.');
    console.error('Example: node decrypt_log.cjs C:\\Users\\user\\Desktop\\BPP_Diagnostics_2026-07-15T03-38-22-123Z.bpplog');
    process.exit(1);
}

const filePath = path.resolve(args[0]);

if (!fs.existsSync(filePath)) {
    console.error(`File not found: ${filePath}`);
    process.exit(1);
}

try {
    const encrypted = fs.readFileSync(filePath, 'utf8');
    
    // AES-256-CBC Decryption
    const encryptionKey = 'bpp_dev_473748';
    const decipher = crypto.createDecipheriv('aes-256-cbc', 
        crypto.scryptSync(encryptionKey, 'salt', 32), 
        Buffer.alloc(16, 0)
    );
    
    let decrypted = decipher.update(encrypted, 'base64', 'utf8');
    decrypted += decipher.final('utf8');
    
    // Pretty print the JSON output
    const jsonOutput = JSON.parse(decrypted);
    console.log(JSON.stringify(jsonOutput, null, 2));
    
    // Optionally save to a .json file for easier reading
    const outPath = filePath.replace('.bpplog', '.json');
    fs.writeFileSync(outPath, JSON.stringify(jsonOutput, null, 2), 'utf8');
    console.log(`\n✅ Decrypted log successfully saved to: ${outPath}`);

} catch (e) {
    console.error('Failed to decrypt the file. Ensure it is a valid .bpplog file generated by the application.');
    console.error(e.message);
}
