
import * as XLSX from 'xlsx';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Employee, PayrollResult, StatutoryConfig, Attendance, LeaveLedger, AdvanceLedger, CompanyProfile } from '../types';
import { BRAND_CONFIG } from '../constants';

// --- Utility: Number to Words (Indian System) ---
export const numberToWords = (num: number): string => {
  const a = ['', 'One ', 'Two ', 'Three ', 'Four ', 'Five ', 'Six ', 'Seven ', 'Eight ', 'Nine ', 'Ten ', 'Eleven ', 'Twelve ', 'Thirteen ', 'Fourteen ', 'Fifteen ', 'Sixteen ', 'Seventeen ', 'Eighteen ', 'Nineteen '];
  const b = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety'];

  const regex = /^(\d{2})(\d{2})(\d{2})(\d{1})(\d{2})$/;
  
  const getLT20 = (n: number) => a[Number(n)];
  const getGT20 = (n: number) => b[Number(n[0])] + ' ' + a[Number(n[1])];

  const numToWords = (input: number): string => {
    if (input === 0) return '';
    
    // Handle large numbers by breaking down
    if (input >= 10000000) { // Crore
        return numToWords(Math.floor(input / 10000000)) + 'Crore ' + numToWords(input % 10000000);
    }
    if (input >= 100000) { // Lakh
        return numToWords(Math.floor(input / 100000)) + 'Lakh ' + numToWords(input % 100000);
    }
    if (input >= 1000) { // Thousand
        return numToWords(Math.floor(input / 1000)) + 'Thousand ' + numToWords(input % 1000);
    }
    if (input >= 100) { // Hundred
        return numToWords(Math.floor(input / 100)) + 'Hundred ' + numToWords(input % 100);
    }
    
    // Less than 100
    if (input < 20) return getLT20(input);
    return getGT20(input.toString() as any); // Type cast for string index access
  };

  const integerPart = Math.floor(num);
  if (integerPart === 0) return 'Zero';
  
  return numToWords(integerPart).trim();
};

const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

const getPeriodsInRange = (startMonth: string, startYear: number, endMonth: string, endYear: number) => {
    const periods: { month: string, year: number }[] = [];
    let currentYear = startYear;
    let currentMonthIdx = MONTHS.indexOf(startMonth);
    const endMonthIdx = MONTHS.indexOf(endMonth);

    // Safety break to prevent infinite loops if logic fails
    let safety = 0;
    while(safety < 60) { // Max 5 years
        periods.push({ month: MONTHS[currentMonthIdx], year: currentYear });

        if (currentYear === endYear && currentMonthIdx === endMonthIdx) break;

        currentMonthIdx++;
        if (currentMonthIdx > 11) {
            currentMonthIdx = 0;
            currentYear++;
        }
        safety++;
    }
    return periods;
};

export const generateExcelReport = (data: any[], sheetName: string, fileName: string) => {
  const ws = XLSX.utils.json_to_sheet(data);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, sheetName);
  XLSX.writeFile(wb, `${fileName}.xlsx`);
};

export const generatePDFTableReport = (
  title: string,
  headers: string[],
  data: (string | number)[][],
  fileName: string,
  orientation: 'p' | 'l' = 'l',
  footnote?: string,
  companyProfile?: CompanyProfile
) => {
  const doc = new jsPDF(orientation, 'mm', 'a4');
  
  // Header - Uses Company Profile or Fallback
  doc.setFontSize(18);
  const companyName = companyProfile?.establishmentName || BRAND_CONFIG.companyName;
  doc.text(companyName, 14, 15);

  // Address - Small Font below Company Name
  doc.setFontSize(8);
  if (companyProfile) {
      const addressLine = `${companyProfile.address}, ${companyProfile.city}, ${companyProfile.state}`.replace(/,\s*,/g, ',');
      doc.text(addressLine, 14, 19);
  }

  doc.setFontSize(11);
  doc.setTextColor(100);
  // Adjusted Y position to account for address line
  doc.text(title, 14, 24);
  doc.setTextColor(0);

  // Table - Adjusted StartY
  autoTable(doc, {
    head: [headers],
    body: data,
    startY: 32,
    theme: 'grid',
    headStyles: { fillColor: [41, 128, 185], textColor: 255, fontSize: 8 },
    bodyStyles: { fontSize: 7 }, // Smaller font for many columns
    styles: { cellPadding: 1 }
  });

  // Footer & Footnote
  const pageCount = doc.getNumberOfPages();
  const finalY = (doc as any).lastAutoTable.finalY + 10;

  if (footnote) {
      doc.setFontSize(8);
      doc.setFont("helvetica", "italic");
      doc.setTextColor(0); // Black for visibility
      // Ensure footnote doesn't go off page
      const printY = finalY > doc.internal.pageSize.height - 20 ? doc.internal.pageSize.height - 20 : finalY;
      doc.text(footnote, 14, printY);
  }

  for(let i = 1; i <= pageCount; i++) {
     doc.setPage(i);
     doc.setFontSize(8);
     doc.setTextColor(150);
     doc.text(`Generated by ${BRAND_CONFIG.appName} on ${new Date().toLocaleDateString()}`, 14, doc.internal.pageSize.height - 10);
     doc.text(`Page ${i} of ${pageCount}`, doc.internal.pageSize.width - 25, doc.internal.pageSize.height - 10);
  }

  doc.save(`${fileName}.pdf`);
};

export const generateSimplePaySheetPDF = (
  results: PayrollResult[],
  employees: Employee[],
  month: string,
  year: number,
  companyProfile?: CompanyProfile
) => {
  const headers = [
    'ID', 'Name', 'Days', 
    'Basic', 'DA', 'Retn', 'HRA', 'Conv', 'Spec', 'Othr', 'Encash', 'GROSS', // Earnings
    'PF', 'VPF', 'ESI', 'PT', 'TDS', 'LWF', 'Adv', 'DED', // Deductions
    'NET PAY'
  ];
  
  let hasCode88 = false;

  const data = results.map(r => {
    const emp = employees.find(e => e.id === r.employeeId);
    const special = r.earnings.special1 + r.earnings.special2 + r.earnings.special3;
    const other = r.earnings.washing + r.earnings.attire;
    
    if (r.isCode88) hasCode88 = true;

    // Add Asterisk to PF amount if Code 88 applies
    const pfDisplay = r.isCode88 
        ? `${Math.round(r.deductions.epf)}*` 
        : Math.round(r.deductions.epf);

    return [
      r.employeeId,
      emp?.name || '',
      r.payableDays,
      Math.round(r.earnings.basic),
      Math.round(r.earnings.da),
      Math.round(r.earnings.retainingAllowance),
      Math.round(r.earnings.hra),
      Math.round(r.earnings.conveyance),
      Math.round(special),
      Math.round(other),
      Math.round(r.earnings.leaveEncashment),
      Math.round(r.earnings.total),
      pfDisplay, // Use formatted PF display
      Math.round(r.deductions.vpf),
      Math.round(r.deductions.esi),
      Math.round(r.deductions.pt),
      Math.round(r.deductions.it),
      Math.round(r.deductions.lwf),
      Math.round(r.deductions.advanceRecovery),
      Math.round(r.deductions.total),
      Math.round(r.netPay)
    ];
  });
  
  const footnote = hasCode88 
    ? "* Code on Social Security 2020 [ Clause 88 ] impact on PF Contribution" 
    : undefined;

  generatePDFTableReport(`Pay Sheet - ${month} ${year}`, headers, data as any[][], `PaySheet_${month}_${year}`, 'l', footnote, companyProfile);
};

export const generatePaySlipsPDF = (
  payrollResults: PayrollResult[],
  employees: Employee[],
  month: string,
  year: number,
  companyProfile?: CompanyProfile
) => {
  const doc = new jsPDF('p', 'mm', 'a4');
  
  payrollResults.forEach((res, index) => {
    if (index > 0) doc.addPage();
    const emp = employees.find(e => e.id === res.employeeId);
    if (!emp) return;

    // --- Header ---
    doc.setFillColor(241, 245, 249); // Slate-100
    doc.rect(0, 0, 210, 40, 'F');
    
    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 41, 59);
    // Dynamic Company Name
    const companyName = companyProfile?.establishmentName || BRAND_CONFIG.companyName;
    doc.text(companyName.toUpperCase(), 105, 18, { align: 'center' });
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(71, 85, 105);
    // Dynamic Address
    const address = companyProfile 
        ? `${companyProfile.address}, ${companyProfile.city}, ${companyProfile.state}` 
        : "Industrial Estate, Chennai, Tamil Nadu";
    doc.text(address, 105, 25, { align: 'center' });
    
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    doc.text(`PAY SLIP - ${month.toUpperCase()} ${year}`, 105, 35, { align: 'center' });

    // --- Employee Details Box ---
    doc.setDrawColor(203, 213, 225);
    doc.rect(14, 45, 182, 35);
    
    const leftX = 18;
    const rightX = 110;
    let y = 52;
    const inc = 6;

    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.text("Employee Name:", leftX, y);
    doc.setFont("helvetica", "normal");
    doc.text(emp.name, leftX + 30, y);
    
    doc.setFont("helvetica", "bold");
    doc.text("Designation:", rightX, y);
    doc.setFont("helvetica", "normal");
    doc.text(emp.designation, rightX + 25, y);

    y += inc;
    doc.setFont("helvetica", "bold");
    doc.text("Employee ID:", leftX, y);
    doc.setFont("helvetica", "normal");
    doc.text(emp.id, leftX + 30, y);

    doc.setFont("helvetica", "bold");
    doc.text("Department:", rightX, y);
    doc.setFont("helvetica", "normal");
    doc.text(emp.division, rightX + 25, y);

    y += inc;
    doc.setFont("helvetica", "bold");
    doc.text("Bank A/c:", leftX, y);
    doc.setFont("helvetica", "normal");
    doc.text(emp.bankAccount, leftX + 30, y);

    doc.setFont("helvetica", "bold");
    doc.text("Days Paid:", rightX, y);
    doc.setFont("helvetica", "normal");
    doc.text(`${res.payableDays} / ${res.daysInMonth}`, rightX + 25, y);
    
    y += inc;
    doc.setFont("helvetica", "bold");
    doc.text("UAN No:", leftX, y);
    doc.setFont("helvetica", "normal");
    doc.text(emp.uanc || 'N/A', leftX + 30, y);
    
    doc.setFont("helvetica", "bold");
    doc.text("PF No:", rightX, y);
    doc.setFont("helvetica", "normal");
    doc.text(emp.pfNumber || 'N/A', rightX + 25, y);
y += inc;
    doc.setFont("helvetica", "bold");
    doc.text("ESI No:", leftX, y);
    doc.setFont("helvetica", "normal");
    doc.text(emp.esiNumber || 'N/A', leftX + 30, y);
    
    doc.setFont("helvetica", "bold");
    doc.text("PAN No:", rightX, y);
    doc.setFont("helvetica", "normal");
    doc.text(emp.pan || 'N/A', rightX + 25, y);

    // --- Financials Table ---
    const startY = 85;
    
     // PF Label Logic: Suffix asterisk to Label if applicable
    const pfLabel = res.isCode88 ? 'Provident Fund*' : 'Provident Fund';
    const pfAmount = res.deductions.epf.toFixed(2); 

    // ESI Label Logic: Suffix double asterisk to Label if applicable
    const esiLabel = res.isESICodeWagesUsed ? 'ESI**' : 'ESI';
    const esiAmount = res.deductions.esi.toFixed(2);

    autoTable(doc, {
        startY: startY,
        margin: { left: 14, right: 14 },
        head: [['Earnings', 'Amount (₹.)', 'Deductions', 'Amount (₹.)']],
        body: [
            ['Basic Pay', res.earnings.basic.toFixed(2), pfLabel, pfAmount ],
            ['DA', res.earnings.da.toFixed(2), esiLabel, esiAmount ],
            ['Retaining Allowance', res.earnings.retainingAllowance.toFixed(2), 'Professional Tax', res.deductions.pt.toFixed(2)],
            ['HRA', res.earnings.hra.toFixed(2), 'Income Tax Recovery', res.deductions.it.toFixed(2)],
            ['Conveyance', res.earnings.conveyance.toFixed(2), 'VPF', res.deductions.vpf.toFixed(2)],
            ['Special Allowance', (res.earnings.special1 + res.earnings.special2 + res.earnings.special3).toFixed(2), 'LWF', res.deductions.lwf.toFixed(2)],
            ['Other Allowances', (res.earnings.washing + res.earnings.attire).toFixed(2), 'Advance Recovery', res.deductions.advanceRecovery.toFixed(2)],
            ['Leave Encashment', res.earnings.leaveEncashment.toFixed(2), '', ''],
            [{ content: 'Total Earnings', styles: { fontStyle: 'bold', fillColor: [241, 245, 249] } }, { content: res.earnings.total.toFixed(2), styles: { fontStyle: 'bold', fillColor: [241, 245, 249] } }, { content: 'Total Deductions', styles: { fontStyle: 'bold', fillColor: [241, 245, 249] } }, { content: res.deductions.total.toFixed(2), styles: { fontStyle: 'bold', fillColor: [241, 245, 249] } }],
        ],
        theme: 'grid',
        headStyles: { fillColor: [51, 65, 85], textColor: 255, halign: 'center' },
        columnStyles: {
            0: { cellWidth: 65 },
            1: { cellWidth: 26, halign: 'right' },
            2: { cellWidth: 65 },
            3: { cellWidth: 26, halign: 'right' },
        }
    });

    // --- Net Pay Section ---
    const finalY = (doc as any).lastAutoTable.finalY + 10;
    
    doc.setDrawColor(59, 130, 246); // Blue border
    doc.setLineWidth(0.5);
    doc.rect(14, finalY, 182, 15);
    
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(15, 23, 42);
    doc.text("NET SALARY PAYABLE:", 20, finalY + 10);
    
    doc.setFontSize(14);
    doc.text(`₹.${Math.round(res.netPay).toLocaleString('en-IN')}/-`, 180, finalY + 10, { align: 'right' });

    // --- Amount in Words ---
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 41, 59);
    const amountWords = numberToWords(Math.round(res.netPay));
    doc.text(`Amount in Words: ${amountWords} Rupees Only`, 14, finalY + 25);

    // --- Footnotes ---
    let footerY = finalY + 35;
    
    if (res.isCode88) {
        doc.setFontSize(8);
        doc.setFont("helvetica", "italic");
        doc.setTextColor(0);
        doc.text("* PF calculated on Code Wages (Social Security Code 2020)", 14, footerY);;
        footerY += 5;
    }
 if (res.isESICodeWagesUsed) {
        doc.setFontSize(8);
        doc.setFont("helvetica", "italic");
        doc.setTextColor(0);
        doc.text("** ESI calculated on Code Wages (Social Security Code 2020)", 14, footerY);
        footerY += 5;
    }
    // --- Footer ---
    doc.setFontSize(8);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(148, 163, 184);
    doc.text("This is a computer-generated document and does not require a signature.", 105, footerY, { align: 'center' });
  });

  doc.save(`PaySlips_${month}_${year}.pdf`);
};

// --- ECR & STATUTORY EXPORTS ---

export const generatePFECR = (
  results: PayrollResult[],
  employees: Employee[],
  format: 'Excel' | 'Text',
  fileName: string
) => {
  const data = results.map(r => {
    const emp = employees.find(e => e.id === r.employeeId);
    const gross = Math.round(r.earnings.total);
    const basicDA = Math.round(r.earnings.basic + r.earnings.da + r.earnings.retainingAllowance);
    const epfWages = Math.min(basicDA, 15000); 
    const epsWages = Math.min(basicDA, 15000);
    const edliWages = Math.min(basicDA, 15000);
    const eeShare = Math.round(r.deductions.epf);
    const epsContri = Math.round(r.employerContributions.eps);
    const erShare = Math.round(r.employerContributions.epf);
    const ncp = Math.max(0, r.daysInMonth - r.payableDays);

    if (format === 'Excel') {
        return {
            'UAN': emp?.uanc,
            'Member Name': emp?.name,
            'Gross Wages': gross,
            'EPF Wages': epfWages,
            'EPS Wages': epsWages,
            'EDLI Wages': edliWages,
            'EE Share': eeShare,
            'EPS Contri': epsContri,
            'ER Share': erShare,
            'NCP Days': ncp,
            'Refunds': 0
        };
    } else {
        return `${emp?.uanc}#~#${emp?.name}#~#${gross}#~#${epfWages}#~#${epsWages}#~#${edliWages}#~#${eeShare}#~#${epsContri}#~#${erShare}#~#${ncp}#~#0`;
    }
  });

  if (format === 'Excel') {
    generateExcelReport(data, 'ECR Data', fileName);
  } else {
    const content = data.join('\n');
    const blob = new Blob([content], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${fileName}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  }
};

export const generateESIReturn = (
    results: PayrollResult[],
    employees: Employee[],
    format: 'Excel' | 'PDF',
    fileName: string,
    companyProfile?: CompanyProfile
) => {
    const data = results.map(r => {
        const emp = employees.find(e => e.id === r.employeeId);
        const ipNumber = emp?.esiNumber || '0000000000';
        const name = emp?.name || '';
        const days = r.payableDays;
        const wages = Math.round(r.earnings.total);
        return {
            'IP Number': ipNumber,
            'IP Name': name,
            'No of Days': days,
            'Total Monthly Wages': wages,
            'Reason Code': '0',
            'Last Working Day': ''
        };
    });

    if (format === 'Excel') {
        generateExcelReport(data, 'ESI Monthly Contribution', fileName);
    } else {
         const headers = ['IP Number', 'Name', 'Days', 'Wages', 'Reason Code'];
         const tableData = data.map(d => [d['IP Number'], d['IP Name'], d['No of Days'], d['Total Monthly Wages'], d['Reason Code']]);
         generatePDFTableReport('Monthly ESI Return Data', headers, tableData, fileName, 'p', undefined, companyProfile);
    }
}

export const generatePTReport = (
    results: PayrollResult[],
    employees: Employee[],
    fileName: string,
    companyProfile?: CompanyProfile
) => {
    const headers = ['Emp ID', 'Name', 'Gross Income', 'PT Deducted'];
    const data = results.map(r => {
        const emp = employees.find(e => e.id === r.employeeId);
        return [
            r.employeeId,
            emp?.name || '',
            Math.round(r.earnings.total),
            Math.round(r.deductions.pt)
        ];
    }).filter(row => (row[3] as number) > 0);

    generatePDFTableReport('Professional Tax Deduction Report', headers, data as any[][], fileName, 'p', undefined, companyProfile);
};

export const generateTDSReport = (
    results: PayrollResult[],
    employees: Employee[],
    fileName: string,
    companyProfile?: CompanyProfile
) => {
    const headers = ['Emp ID', 'Name', 'PAN', 'Gross Income', 'TDS Deducted'];
    const data = results.map(r => {
        const emp = employees.find(e => e.id === r.employeeId);
        return [
            r.employeeId,
            emp?.name || '',
            emp?.pan || '',
            Math.round(r.earnings.total),
            Math.round(r.deductions.it)
        ];
    }).filter(row => (row[4] as number) > 0);

    generatePDFTableReport('Income Tax (TDS) Deduction Report', headers, data as any[][], fileName, 'p', undefined, companyProfile);
};

export const generateCodeOnWagesReport = (
    results: PayrollResult[],
    employees: Employee[],
    format: 'Excel' | 'PDF',
    fileName: string,
    companyProfile?: CompanyProfile
) => {
    const data = results.map(r => {
        const emp = employees.find(e => e.id === r.employeeId);
        const wageA = r.earnings.basic + r.earnings.da + r.earnings.retainingAllowance;
        const wageB = r.earnings.total;
        const wageC = wageB - wageA;
        const limit = wageB * 0.5;
        const excess = Math.max(0, wageC - limit);
        const pfWage = wageA + excess;

        return {
            'Emp ID': r.employeeId,
            'Name': emp?.name,
            'Gross (B)': Math.round(wageB),
            'Basic+DA (A)': Math.round(wageA),
            'Allowances (C)': Math.round(wageC),
            '50% of Gross': Math.round(limit),
            'Excess (D)': Math.round(excess),
            'PF Wage (A+D)': Math.round(pfWage),
            'Impact': excess > 0 ? 'YES' : 'NO'
        };
    });

    if (format === 'Excel') {
        generateExcelReport(data, 'Code 88 Analysis', fileName);
    } else {
        const headers = ['ID', 'Name', 'Gross', 'Basic+DA', 'Allw', '50% Limit', 'Excess', 'PF Wage', 'Impact'];
        const tableData = data.map(d => [d['Emp ID'], d['Name'], d['Gross (B)'], d['Basic+DA (A)'], d['Allowances (C)'], d['50% of Gross'], d['Excess (D)'], d['PF Wage (A+D)'], d['Impact']]);
        generatePDFTableReport('Code on Wages (Clause 88) Impact Analysis', headers, tableData as any[][], fileName, 'l', undefined, companyProfile);
    }
};

// --- NEW Form 12A (Revised) & Old Form 12 ---

export const generatePFForm12 = (
    results: PayrollResult[],
    employees: Employee[],
    config: StatutoryConfig,
    month: string,
    year: number,
    companyProfile?: CompanyProfile
) => {
    // OLD Form 12 (Monthly Statement) Logic
    let totalWages = 0;
    let totalEEShare = 0;
    let totalERShare = 0;
    let totalPension = 0;
    let totalAdminCharges = 0;
    let totalEDLI = 0;

    results.forEach(r => {
        const basicDA = r.earnings.basic + r.earnings.da + r.earnings.retainingAllowance;
        const gross = r.earnings.total;
        let wageD = 0;
        if (gross > 0 && ((gross - basicDA)/gross) > 0.5) wageD = (gross - basicDA) - (gross * 0.5);
        const pfWage = Math.min(basicDA + wageD, config.epfCeiling);

        totalWages += pfWage;
        totalEEShare += r.deductions.epf;
        totalERShare += r.employerContributions.epf;
        totalPension += r.employerContributions.eps;
    });

    totalAdminCharges = Math.max(500, Math.round(totalWages * 0.005));
    totalEDLI = Math.round(totalWages * 0.005);

    const headers = ['Particulars', 'A/c No. 1 (PF)', 'A/c No. 2 (Admin)', 'A/c No. 10 (Pension)', 'A/c No. 21 (EDLI)', 'A/c No. 22 (Admin)', 'Total'];
    const data = [
        ['Employer\'s Share', Math.round(totalERShare), '', Math.round(totalPension), Math.round(totalEDLI), '', ''],
        ['Employee\'s Share', Math.round(totalEEShare), '', '', '', '', ''],
        ['Admin Charges', '', Math.round(totalAdminCharges), '', '', '0', ''],
        ['Total Remittance', 
            Math.round(totalERShare + totalEEShare), 
            Math.round(totalAdminCharges), 
            Math.round(totalPension), 
            Math.round(totalEDLI), 
            '0', 
            Math.round(totalERShare + totalEEShare + totalAdminCharges + totalPension + totalEDLI)
        ]
    ];
    
    data[0][6] = (data[0][1] as number + (data[0][3] as number) + (data[0][4] as number)).toString();
    data[1][6] = (data[1][1] as number).toString();
    data[2][6] = (data[2][2] as number).toString();

    generatePDFTableReport(`Form 12 - Monthly Statement for ${month} ${year}`, headers, data as any[][], `Form12_Old_${month}_${year}`, 'p', `Total Subscribers: ${results.length}`, companyProfile);
};

export const generatePFForm12A = (
    results: PayrollResult[],
    employees: Employee[],
    config: StatutoryConfig,
    companyProfile: CompanyProfile,
    month: string,
    year: number
) => {
    // NEW Form 12A (Revised) Logic - Calculation Sheet Layout
    let totalUncappedPFWages = 0; // The wage used for "PF-Wages" display (A+D without cap)
    let totalPFWages = 0; // Capped for EPF (12%)
    let totalEPSWages = 0; // Capped for EPS (8.33%)
    let totalEDLIWages = 0; // Capped for EDLI (0.5%)
    let totalEEShare = 0;
    let totalEREPS = 0;
    let totalEREPF = 0;

    results.forEach(r => {
        const emp = employees.find(e => e.id === r.employeeId);
        // Calculate wages per employee to sum up accurately
        const basicDA = r.earnings.basic + r.earnings.da + r.earnings.retainingAllowance;
        const gross = r.earnings.total;
        let wageD = 0;
        if (gross > 0 && ((gross - basicDA)/gross) > 0.5) wageD = (gross - basicDA) - (gross * 0.5);
        
        const uncappedWage = basicDA + wageD;
        totalUncappedPFWages += uncappedWage;

        // Capped Wages for Contribution Calculation
        const cappedWage = Math.min(uncappedWage, config.epfCeiling);
        // Use logic from payroll engine: if higher wages opted, use uncapped
        const pfWage = (emp?.isPFHigherWages) ? uncappedWage : cappedWage;
        
        totalPFWages += pfWage;
        totalEPSWages += pfWage; // Usually same cap
        totalEDLIWages += pfWage; // Usually same cap

        totalEEShare += r.deductions.epf;
        totalEREPS += r.employerContributions.eps;
        totalEREPF += r.employerContributions.epf;
    });

    const adminCharges = Math.max(500, Math.round(totalPFWages * 0.005));
    const edliCharges = Math.round(totalEDLIWages * 0.005);

    const doc = new jsPDF('p', 'mm', 'a4');
    
    // --- Header Layout ---
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(200, 0, 0); // Red
    doc.text("PF_Form12A (Revised)", 105, 10, { align: 'center' });
    doc.setTextColor(0); // Reset

    // Left Block
    const leftX = 14;
    let y = 20;
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.text("(Only for Un-Exempted Establishment)", leftX, y); y += 5;
    doc.text("Name Address of Establishment", leftX, y); y += 5;
    
    doc.setFontSize(11);
    doc.text(companyProfile.establishmentName || BRAND_CONFIG.companyName, leftX, y); y += 5;
    
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text(companyProfile.city ? `${companyProfile.city}, ${companyProfile.state}` : "Industrial Estate, Chennai, TN", leftX, y); y += 5;
    doc.text(companyProfile.address || "#6, VANAGARAM MAIN ROAD AYNAMBAKKA", leftX, y);

    // --- Middle Column (Act Info) ---
    const midX = 80; 
    let midY = 20;
    doc.setFontSize(9);
    
    const drawMidLine = (text: string) => {
        doc.text("| " + text, midX, midY);
        midY += 5;
    };

    drawMidLine("Employees Provident Fund And Misc. Provision Act 1952");
    drawMidLine("Employees Pension Scheme [Paragraph 20 (4)]");
    drawMidLine("Currency Period from: 1st " + month + " to " + new Date(year, MONTHS.indexOf(month)+1, 0).getDate() + " " + month); 
    drawMidLine(`Statement of Contribution for the Month of ${month} ${year}`);

    // --- Right Column (EPFO Info) - Parallel ---
    const rightX = 170; 
    let rightY = 20; // Start at same height as Middle Column
    
    const drawRightLine = (text: string) => {
        doc.text("| " + text, rightX, rightY);
        rightY += 5;
    };

    drawRightLine("(To be Filled by the EPFO)"); 
    drawRightLine("Establishment Status");
    drawRightLine("Group Code");
    drawRightLine("Establishment Code");

    // Title Section
    let titleY = Math.max(y, midY) + 7;
    
    // Add Red Lines above and below the title to match format
    doc.setDrawColor(200, 0, 0); // Red
    doc.setLineWidth(0.5);
    doc.line(14, titleY - 6, 205, titleY - 6); // Top line

    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(200, 0, 0);
    doc.text("PF ECR_UAN_CALCULATION SHEET", 105, titleY, { align: 'center' });
    doc.setTextColor(0); // Reset to black

    doc.line(14, titleY + 2, 205, titleY + 2); // Bottom line

    // TRRN & Date Boxes
    titleY += 10;
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    
    // Yellow Box 1 - TRRN
    doc.setFillColor(255, 255, 0); // Yellow
    doc.rect(70, titleY - 4, 20, 6, 'F'); // Fill Rect
    doc.setTextColor(0); // Black Text
    doc.text("TRRN", 80, titleY, { align: 'center' });
    
    // Yellow Box 2 - Date
    // Explicitly resetting fill and text color to ensure "Date" is not blocked black
    doc.setFillColor(255, 255, 0); // Ensure Yellow Background
    doc.rect(150, titleY - 4, 20, 6, 'F'); // Fill Rect
    doc.setTextColor(0); // Black Text
    doc.text("Date", 160, titleY, { align: 'center' });

    // --- Calculation Table ---
    // The structure is specific:
    // Row 1: "PF-Wages" [Value] "Employee Share" "Employer Share" "Total"
    // And styling needs to be bold.

    // Row 1: EPF Wages(A/c No.1)
    const row1_Total = Math.round(totalEEShare + totalEREPF);
    
    // Row 2: EPS Wages(A/c No.10)
    const row2_Total = Math.round(totalEREPS);

    // Row 3: EDLI Wages(A/c No.21)
    const row3_Total = Math.round(edliCharges);

    // Row 4: Admin Charges(A/c No.2)
    const row4_Total = Math.round(adminCharges);

    // Grand Total
    const grandTotal_EE = Math.round(totalEEShare);
    // Note: Admin Charges and EDLI are Employer costs but visually appear in "Total" column in grid rows.
    // For the specific cell in "Employer Share" column of Total Row, the screenshot shows 4494 (EPF 1374 + EPS 3120).
    const displayTotal_ER_Column = Math.round(totalEREPF + totalEREPS); 
    const grandTotal_All = Math.round(row1_Total + row2_Total + row3_Total + row4_Total); 

    const tableData = [
        // Custom Header Row simulated as first body row to control style
        [
            { content: 'PF-Wages', styles: { fontStyle: 'bold', fontSize: 10 } }, 
            { content: Math.round(totalUncappedPFWages).toString(), styles: { fontStyle: 'bold', fontSize: 10 } }, 
            { content: 'Employee Share', styles: { fontStyle: 'bold', fontSize: 10 } }, 
            { content: 'Employer Share', styles: { fontStyle: 'bold', fontSize: 10 } }, 
            { content: 'Total', styles: { fontStyle: 'bold', fontSize: 10 } }
        ],
        // Data Rows
        [
            { content: 'EPF_Wages (A/c No.1) (12%+3.67%)', styles: { fontStyle: 'bold' } }, 
            Math.round(totalPFWages), 
            `12%       ${Math.round(totalEEShare)}`, 
            `3.67%       ${Math.round(totalEREPF)}`, 
            row1_Total
        ],
        [
            { content: 'EPS_Wages (A/c No.10) (8.33%)', styles: { fontStyle: 'bold' } }, 
            Math.round(totalEPSWages), 
            '', 
            `8.33%       ${Math.round(totalEREPS)}`, 
            row2_Total
        ],
        [
            { content: 'EDLI_Wages (A/c No.21) (0.50%)', styles: { fontStyle: 'bold' } }, 
            Math.round(totalEDLIWages), 
            '', 
            '', 
            row3_Total
        ],
        [
            { content: 'Admin_Charges (A/c No.2) (0.50%)', styles: { fontStyle: 'bold' } }, 
            Math.round(totalPFWages), 
            '', 
            '', 
            row4_Total
        ],
        [
            { content: 'Admin_Charg_EDLI (0.0%)', styles: { fontStyle: 'bold' } }, 
            '0', 
            '', 
            '', 
            '0'
        ],
        // Total Row
        [
            { content: '', styles: { fillColor: [255, 255, 255] } },
            '',
            { content: Math.round(grandTotal_EE), styles: { fontStyle: 'bold', fontSize: 10 } },
            { content: Math.round(displayTotal_ER_Column), styles: { fontStyle: 'bold', fontSize: 10 } },
            { content: Math.round(grandTotal_All), styles: { fontStyle: 'bold', fontSize: 10 } }
        ]
    ];

    autoTable(doc, {
        startY: titleY + 10,
        body: tableData as any,
        theme: 'plain', // Removing default striping to match white/clean look
        styles: { fontSize: 9, cellPadding: 3, halign: 'right', lineColor: 200, lineWidth: 0 }, // Minimal borders, mainly relying on spacing
        columnStyles: { 
            0: { halign: 'left', cellWidth: 50 },
            1: { halign: 'right', cellWidth: 30 },
            2: { halign: 'right' },
            3: { halign: 'right' },
            4: { halign: 'right' }
        },
        didParseCell: (data) => {
            // Add top/bottom borders for the "Total" row (last row)
            if (data.row.index === tableData.length - 1) {
                data.cell.styles.lineWidth = { top: 0.1, bottom: 0.1 };
                data.cell.styles.lineColor = [150, 150, 150];
            }
            // Add red line below the "PF-Wages" header row (first row)
            if (data.row.index === 0) {
                 data.cell.styles.lineWidth = { bottom: 0.5 };
                 data.cell.styles.lineColor = [200, 0, 0];
                 data.cell.styles.textColor = [0, 0, 0];
            }
        }
    });

    doc.save(`PF_Form12A_Revised_${month}_${year}.pdf`);
};

export const generateFormB = (
  results: PayrollResult[],
  employees: Employee[],
  month: string,
  year: number,
  companyProfile?: CompanyProfile
) => {
   const headers = ['Sl.No', 'Name', 'Designation', 'Total Days', 'Basic', 'DA', 'Allowances', 'Gross Wages', 'PF', 'ESI', 'Other Ded', 'Total Ded', 'Net Wages'];
   const data = results.map((r, i) => {
       const emp = employees.find(e => e.id === r.employeeId);
       const otherAllow = r.earnings.total - (r.earnings.basic + r.earnings.da);
       const otherDed = r.deductions.total - (r.deductions.epf + r.deductions.esi);
       return [
           i + 1,
           emp?.name || '',
           emp?.designation || '',
           r.payableDays,
           Math.round(r.earnings.basic),
           Math.round(r.earnings.da),
           Math.round(otherAllow),
           Math.round(r.earnings.total),
           Math.round(r.deductions.epf),
           Math.round(r.deductions.esi),
           Math.round(otherDed),
           Math.round(r.deductions.total),
           Math.round(r.netPay)
       ];
   });
   
   generatePDFTableReport(`FORM B [See Rule 21] - Register of Wages - ${month} ${year}`, headers, data as any[][], `FormB_${month}_${year}`, 'l', undefined, companyProfile);
};

export const generateCentralWageSlip = (
  results: PayrollResult[],
  employees: Employee[],
  month: string,
  year: number
) => {
   generatePaySlipsPDF(results, employees, month, year);
};

export const generateFormC = (
    results: PayrollResult[],
    employees: Employee[],
    attendance: Attendance[],
    month: string,
    year: number,
    companyProfile?: CompanyProfile
) => {
    const headers = ['Sl.No', 'Name', 'Father/Husband', 'Sex', 'Designation', 'Present', 'Leaves', 'Work Done (Days)'];
    const data = results.map((r, i) => {
        const emp = employees.find(e => e.id === r.employeeId);
        const att = attendance.find(a => a.employeeId === r.employeeId);
        const leaves = (att?.earnedLeave || 0) + (att?.sickLeave || 0) + (att?.casualLeave || 0);
        return [
            i + 1,
            emp?.name || '',
            emp?.fatherSpouseName || '',
            emp?.gender || '',
            emp?.designation || '',
            att?.presentDays || 0,
            leaves,
            r.payableDays
        ];
    });

    generatePDFTableReport(`FORM D [See Rule 17] - Register of Attendance - ${month} ${year}`, headers, data as any[][], `FormC_MusterRoll_${month}_${year}`, 'l', "Note: Summary Muster Roll generated based on monthly aggregates.", companyProfile);
};

export const generatePFForm3A = (
  allHistory: PayrollResult[],
  employees: Employee[],
  config: StatutoryConfig,
  startMonth: string,
  startYear: number,
  endMonth: string,
  endYear: number,
  singleEmployeeId?: string
) => {
  const doc = new jsPDF('p', 'mm', 'a4');
  const periods = getPeriodsInRange(startMonth, startYear, endMonth, endYear);
  const targetEmployees = singleEmployeeId 
    ? employees.filter(e => e.id === singleEmployeeId)
    : employees;

  if (targetEmployees.length === 0) {
      alert("No employees found for report generation.");
      return;
  }

  targetEmployees.forEach((emp, index) => {
    if (index > 0) doc.addPage();
    const empRecords = allHistory.filter(r => r.employeeId === emp.id);

    // --- Header ---
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("For UnExempted Establishment Only ( Form 3A Revised)", 105, 10, { align: 'center' });
    doc.text("The Employees Provident Fund Scheme 1952 (Paras 35 & 42)", 105, 15, { align: 'center' });
    doc.text("The Employees Pension Scheme: 1995 (Para 19)", 105, 20, { align: 'center' });
    
    doc.setFontSize(9);
    doc.text(`Contribution Card for Currency Period from: 01 ${startMonth} ${startYear} to 31 ${endMonth} ${endYear}`, 105, 28, { align: 'center' });

    // --- Employee Info Block ---
    const startY = 35;
    doc.text(`Account No: ${emp.pfNumber || 'TB/TAM/------'}`, 14, startY);
    doc.text(`Name/Surname: ${emp.name}`, 14, startY + 6);
    doc.text(`Father/Husband Name: ${emp.fatherSpouseName}`, 14, startY + 12);
    
    doc.text(`Name_Address of Factory/Establishment:`, 110, startY);
    doc.setFont("helvetica", "bold");
    doc.text(BRAND_CONFIG.companyName, 110, startY + 6);
    doc.setFont("helvetica", "normal");
    doc.text("Industrial Estate, Chennai, TN", 110, startY + 12);

    doc.text("Statutory Rate of Cont: 12%", 14, startY + 20);
    doc.text("Voluntary Higher Rate: " + (emp.employeeVPFRate > 0 ? `${emp.employeeVPFRate}%` : 'NIL'), 110, startY + 20);

    // --- Table Data Preparation ---
    let totalWages = 0;
    let totalWorkerShare = 0;
    let totalEmployerEPF = 0;
    let totalPension = 0;

    const tableData = periods.map(p => {
        const rec = empRecords.find(r => 
            r.month.trim().toLowerCase() === p.month.trim().toLowerCase() && 
            r.year === p.year
        );
        
        if (rec) {
            const basic = rec.earnings.basic + rec.earnings.da + rec.earnings.retainingAllowance;
            const gross = rec.earnings.total;
            let wageD = 0;
            if (gross > 0 && ((gross - basic)/gross) > 0.5) {
                wageD = (gross - basic) - (gross * 0.5);
            }
            const pfWages = Math.min(basic + wageD, config.epfCeiling); 

            const workerShare = Math.round(rec.deductions.epf);
            const pension = Math.round(rec.employerContributions.eps);
            const employerEPF = Math.round(rec.employerContributions.epf); 
            
            totalWages += pfWages;
            totalWorkerShare += workerShare;
            totalEmployerEPF += employerEPF;
            totalPension += pension;

            const ncpDays = Math.max(0, rec.daysInMonth - rec.payableDays);

            return [
                `${p.month.substring(0,3)} '${p.year.toString().substring(2)}`,
                pfWages,
                workerShare,
                employerEPF,
                pension,
                '', 
                ncpDays > 0 ? ncpDays : '' 
            ];
        } else {
            return [
                `${p.month.substring(0,3)} '${p.year.toString().substring(2)}`,
                '', '', '', '', '', ''
            ];
        }
    });

    // Totals Row
    tableData.push([
        'Total :',
        totalWages,
        totalWorkerShare,
        totalEmployerEPF,
        totalPension,
        '',
        ''
    ]);

    // --- Table ---
    autoTable(doc, {
        startY: startY + 28,
        head: [[
            { content: "Month Paid in", rowSpan: 2 },
            { content: "Amount of Wages", rowSpan: 2 },
            { content: "Worker's Share", rowSpan: 2 },
            { content: "Employer's Share", colSpan: 2, styles: { halign: 'center' } },
            { content: "Ref. of Adv", rowSpan: 2 },
            { content: "NCP Days", rowSpan: 2 }
        ],
        ['EPF', 'Pension Fund']],
        body: tableData,
        theme: 'plain',
        styles: { fontSize: 9, cellPadding: 2, lineWidth: 0.1, lineColor: 0, halign: 'center' },
        columnStyles: { 0: { halign: 'left' } },
        didParseCell: (data) => {
            if (data.section === 'body' && data.row.index === periods.length) {
                data.cell.styles.fontStyle = 'bold';
                data.cell.styles.lineWidth = { top: 0.2, bottom: 0.2, left: 0.1, right: 0.1 };
            }
        }
    });

    const finalY = (doc as any).lastAutoTable.finalY + 10;
    
    // --- Footer Certification ---
    doc.setFontSize(8);
    doc.text("Certified that the total amount of contribution (both shares) indicated in this card i.e. Rs. " + (totalWorkerShare + totalEmployerEPF + totalPension) + " has already been remitted in full.", 14, finalY);
    
    doc.setFont("helvetica", "bold");
    doc.text("For " + BRAND_CONFIG.companyName, 140, finalY + 15);
    doc.text("Signature of employer with Official Seal", 140, finalY + 30);
  });

  doc.save(`PF_Form3A_${startMonth}${startYear}_to_${endMonth}${endYear}.pdf`);
};

export const generatePFForm6A = (
  allHistory: PayrollResult[],
  employees: Employee[],
  config: StatutoryConfig,
  startMonth: string,
  startYear: number,
  endMonth: string,
  endYear: number
) => {
  const doc = new jsPDF('l', 'mm', 'a4');
  const periods = getPeriodsInRange(startMonth, startYear, endMonth, endYear);

  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(180, 0, 0);
  doc.text("Form 6A", 148, 10, { align: 'center' });
  doc.setTextColor(0);
  
  doc.setFontSize(10);
  doc.text(`Statement of Contribution for the Period From 01 ${startMonth} ${startYear} To 31 ${endMonth} ${endYear}`, 148, 16, { align: 'center' });
  
  doc.setFontSize(9);
  doc.text(`Name of Establishment: ${BRAND_CONFIG.companyName}`, 14, 25);
  doc.text("Address: Industrial Estate, Chennai, TN", 14, 30);
  doc.text("Statutory Rate: 12%", 250, 25);

  const headers = [
    [
      { content: 'Sl No', rowSpan: 2 },
      { content: 'PF Account No', rowSpan: 2 },
      { content: 'Name of the Member', rowSpan: 2 },
      { content: 'Wages', rowSpan: 2 },
      { content: 'Worker\'s Share', rowSpan: 2 },
      { content: 'Employer\'s Share', colSpan: 2, styles: { halign: 'center' as 'center' } },
      { content: 'Total', rowSpan: 2 },
      { content: 'Remarks', rowSpan: 2 }
    ],
    ['EPF Diff', 'Pension Fund']
  ];

  const data = employees.map((emp, i) => {
      const empRecords = allHistory.filter(r => 
          r.employeeId === emp.id && 
          periods.some(p => r.month.trim().toLowerCase() === p.month.trim().toLowerCase() && r.year === p.year)
      );

      let wages = 0;
      let eeShare = 0;
      let erEPF = 0;
      let erPension = 0;

      empRecords.forEach(rec => {
          const basic = rec.earnings.basic + rec.earnings.da + rec.earnings.retainingAllowance;
          const gross = rec.earnings.total;
          let wageD = 0;
          if (gross > 0 && ((gross - basic)/gross) > 0.5) wageD = (gross - basic) - (gross * 0.5);
          const pfWage = Math.min(basic + wageD, config.epfCeiling);

          wages += pfWage;
          eeShare += rec.deductions.epf;
          erEPF += rec.employerContributions.epf;
          erPension += rec.employerContributions.eps;
      });

      if (wages === 0) return [];

      return [
          i + 1,
          emp.pfNumber || 'N/A',
          emp.name,
          wages,
          eeShare,
          erEPF,
          erPension,
          erEPF + erPension,
          ''
      ];
  }).filter(row => row.length > 0);

  autoTable(doc, {
      head: headers,
      body: data,
      startY: 35,
      theme: 'grid',
      styles: { fontSize: 8, cellPadding: 2, halign: 'center' },
      headStyles: { fillColor: [255, 255, 255], textColor: 0, lineWidth: 0.1 }
  });

  const finalY = (doc as any).lastAutoTable.finalY + 10;
  
  let grandWages = 0, grandEE = 0, grandErEPF = 0, grandErPension = 0;
  data.forEach((row: any) => {
      grandWages += row[3];
      grandEE += row[4];
      grandErEPF += row[5];
      grandErPension += row[6];
  });

  doc.setFont("helvetica", "bold");
  doc.text("Grand Total:", 14, finalY);
  doc.text(`Wages: ${grandWages}`, 50, finalY);
  doc.text(`EE Share: ${grandEE}`, 90, finalY);
  doc.text(`ER EPF: ${grandErEPF}`, 130, finalY);
  doc.text(`Pension: ${grandErPension}`, 170, finalY);

  doc.text("For " + BRAND_CONFIG.companyName, 220, finalY + 15);
  doc.text("Signature of Employer", 220, finalY + 25);

  doc.save(`PF_Form6A_${startMonth}${startYear}_to_${endMonth}${endYear}.pdf`);
};

export const generateTNFormR = (
  results: PayrollResult[],
  employees: Employee[],
  month: string,
  year: number,
  companyProfile?: CompanyProfile
) => {
    const headers = ['S.No', 'Name', 'Basic', 'DA', 'HRA', 'OT', 'Other', 'Gross', 'PF', 'ESI', 'Adv', 'Total Ded', 'Net'];
    const data = results.map((r, i) => {
        const emp = employees.find(e => e.id === r.employeeId);
        return [
            i+1, emp?.name || '', 
            r.earnings.basic, r.earnings.da, r.earnings.hra, 0,
            (r.earnings.total - r.earnings.basic - r.earnings.da - r.earnings.hra),
            r.earnings.total,
            r.deductions.epf, r.deductions.esi, r.deductions.advanceRecovery,
            r.deductions.total, r.netPay
        ];
    });
    generatePDFTableReport(`TN Form R (Register of Wages) - ${month} ${year}`, headers, data as any[][], `TN_FormR_${month}_${year}`, 'l', undefined, companyProfile);
};

export const generateTNFormT = (
  results: PayrollResult[],
  employees: Employee[],
  attendance: Attendance[],
  leaveLedgers: LeaveLedger[],
  month: string,
  year: number,
  companyProfile?: CompanyProfile
) => {
    const headers = ['ID', 'Name', 'EL Opn', 'EL Avl', 'EL Bal', 'Wages', 'Deductions', 'Net'];
    const data = results.map(r => {
        const emp = employees.find(e => e.id === r.employeeId);
        const l = leaveLedgers.find(led => led.employeeId === r.employeeId);
        const att = attendance.find(a => a.employeeId === r.employeeId);
        return [
            r.employeeId, emp?.name || '',
            l?.el.opening || 0,
            att?.earnedLeave || 0,
            l?.el.balance || 0,
            r.earnings.total,
            r.deductions.total,
            r.netPay
        ];
    });
    generatePDFTableReport(`TN Form T (Wage Slips Summary) - ${month} ${year}`, headers, data as any[][], `TN_FormT_${month}_${year}`, 'l', undefined, companyProfile);
};

export const generateTNFormP = (
  results: PayrollResult[],
  employees: Employee[],
  advanceLedgers: AdvanceLedger[],
  month: string,
  year: number,
  companyProfile?: CompanyProfile
) => {
    const headers = ['ID', 'Name', 'Advance Date', 'Amount', 'Purpose', 'Recovered', 'Balance'];
    const data = results.map(r => {
        const emp = employees.find(e => e.id === r.employeeId);
        const adv = advanceLedgers.find(a => a.employeeId === r.employeeId);
        if (!adv || (adv.balance === 0 && adv.totalAdvance === 0 && r.deductions.advanceRecovery === 0)) return null;
        
        return [
            r.employeeId, emp?.name || '',
            '',
            adv.totalAdvance,
            'Salary Advance',
            r.deductions.advanceRecovery,
            adv.balance
        ];
    }).filter(x => x !== null);
    
    if (data.length === 0) {
        data.push(['', 'No Advances', '', '', '', '', '']);
    }

    generatePDFTableReport(`TN Form P (Register of Advances) - ${month} ${year}`, headers, data as any[][], `TN_FormP_${month}_${year}`, 'l', undefined, companyProfile);
};

export const generateESICodeWagesReport = (
    results: PayrollResult[],
    employees: Employee[],
    format: 'Excel' | 'PDF',
    fileName: string,
    companyProfile?: CompanyProfile
) => {
    const data = results.map(r => {
        const emp = employees.find(e => e.id === r.employeeId);
        // ESI is typically calculated on Gross Wages. 
        // Code on Wages 2020 might define wages differently (similar to PF) but for ESI currently it's usually Gross.
        // This report highlights the wages considered for ESI vs Gross.
        const gross = Math.round(r.earnings.total);
        const esiWages = (r.deductions.esi > 0 || r.employerContributions.esi > 0) ? gross : 0;
        
        return {
            'Emp ID': r.employeeId,
            'Name': emp?.name,
            'Gross Wages': gross,
            'ESI Wages': esiWages,
            'EE Contribution': Math.round(r.deductions.esi),
            'ER Contribution': Math.round(r.employerContributions.esi),
            'Coverage': esiWages > 0 ? 'YES' : 'NO'
        };
    });

    if (format === 'Excel') {
        generateExcelReport(data, 'ESI Wages Analysis', fileName);
    } else {
        const headers = ['ID', 'Name', 'Gross', 'ESI Wage', 'EE Share', 'ER Share', 'Covered'];
        const tableData = data.map(d => [d['Emp ID'], d['Name'], d['Gross Wages'], d['ESI Wages'], d['EE Contribution'], d['ER Contribution'], d['Coverage']]);
        generatePDFTableReport('ESI Wages & Contribution Report', headers, tableData as any[][], fileName, 'p', undefined, companyProfile);
    }
};

export const generateESIExitReport = (
    results: PayrollResult[],
    employees: Employee[],
    month: string,
    year: number,
    companyProfile?: CompanyProfile
) => {
    const headers = ['ID', 'Name', 'Gross Wages', 'Reason'];
    
    // Filter for employees with 0 ESI deduction
    const data = results
        .filter(r => r.deductions.esi === 0)
        .map(r => {
             const emp = employees.find(e => e.id === r.employeeId);
             const gross = r.earnings.total;
             let reason = 'Unknown';
             if (emp?.isESIExempt) reason = 'Exempt (Policy)';
             else if (gross > 21000) reason = 'Salary > 21k';
             else reason = 'Zero Earnings / LOP';
             
             return [
                 r.employeeId,
                 emp?.name || '',
                 Math.round(gross),
                 reason
             ];
        });

    generatePDFTableReport(`ESI Excluded Employees - ${month} ${year}`, headers, data as any[][], `ESI_Exit_Report_${month}_${year}`, 'p', undefined, companyProfile);
};
